const data = [
	{
		link: '',
		image: '/img/products/card-img-2.png',
		title: 'Coat Vivaldi',
		text: 'Store',
		price: '14 500 ₽',
		originalPrice: '28 400 ₽',
	},
	{
		link: '',
		image: '/img/products/card-img-3.png',
		title: 'Coat Vivaldi',
		text: 'Store',
		price: '14 500 ₽',
		originalPrice: '28 400 ₽',
	},
	{
		link: '',
		image: '/img/products/card-img-4.png',
		title: 'Coat Vivaldi',
		text: 'Store',
		price: '14 500 ₽',
		originalPrice: '28 400 ₽',
	},
	{
		link: '',
		image: '/img/products/card-img-1.png',
		title: 'Coat Vivaldi',
		text: 'Store',
		price: '14 500 ₽',
		originalPrice: '28 400 ₽',
	},
	{
		link: '',
		image: '/img/products/card-img-2.png',
		title: 'Coat Vivaldi',
		text: 'Store',
		price: '14 500 ₽',
		originalPrice: '28 400 ₽',
	},
	{
		link: '',
		image: '/img/products/card-img-3.png',
		title: 'Coat Vivaldi',
		text: 'Store',
		price: '14 500 ₽',
		originalPrice: '28 400 ₽',
	},
	{
		link: '',
		image: '/img/products/card-img-4.png',
		title: 'Coat Vivaldi',
		text: 'Store',
		price: '14 500 ₽',
		originalPrice: '28 400 ₽',
	},
	{
		link: '',
		image: '/img/products/card-img-1.png',
		title: 'Coat Vivaldi',
		text: 'Store',
		price: '14 500 ₽',
		originalPrice: '28 400 ₽',
	},
	{
		link: '',
		image: '/img/products/card-img-2.png',
		title: 'Coat Vivaldi',
		text: 'Store',
		price: '14 500 ₽',
		originalPrice: '28 400 ₽',
	},
	{
		link: '',
		image: '/img/products/card-img-3.png',
		title: 'Coat Vivaldi',
		text: 'Store',
		price: '14 500 ₽',
		originalPrice: '28 400 ₽',
	},
	{
		link: '',
		image: '/img/products/card-img-4.png',
		title: 'Coat Vivaldi',
		text: 'Store',
		price: '14 500 ₽',
		originalPrice: '28 400 ₽',
	},
	{
		link: '',
		image: '/img/products/card-img-1.png',
		title: 'Coat Vivaldi',
		text: 'Store',
		price: '14 500 ₽',
		originalPrice: '28 400 ₽',
	},
]

export default data